### ISSUE TITLE
weird checksum error

### ISSUE THREAD

**Issue by gobaoscar** [solsticegamestudios/GModCEFCodecFix#116]
when needing to update/fix the menu, theres a checksum error, dificulting the task, needing to verify the game and try again, and sometimes, the fix does broke in no time, on windows, linux and macos (i guess)

**Comment by AkikoKumagara** [comment]
Usually happens when GMod is updated and our manifest (containing the checksums of files to patch) hasn't yet updated.

Assuming that's the issue, there's not much that can be done about this, unfortunately. We sometimes manually regenerate our manifest as soon as we can, but it's a process which in total takes around 45 minutes and runs on an automated schedule every 6 hours.

Rest assured, this issue affects everyone the same when it does happen, again under the assumption the above is what you mean.

**Comment by Lucas-V-L** [comment]
would it be possible to set it up to track updates and regenerate as soon as there's an update? i usually hop on the game with my friends at around 10pm chicago time and if theres an update i just cant play that night :(

**Comment by AkikoKumagara** [comment]
> would it be possible to set it up to track updates and regenerate as soon as there's an update? i usually hop on the game with my friends at around 10pm chicago time and if theres an update i just cant play that night :(

Doesn't work because each commit is an "update", and they often roll in back to back. By the time the manifest is regenerated once (a 45 minute process) it would too often immediately need to regenerate again.
This solution isn't really something we can do.

**Comment by WinterPhoenix** [comment]
GMod updates typically don't happen after about 6PM Eastern Time, and we have manifest regeneration automatically run at 6PM so it's ready by ~7PM
