### ISSUE TITLE
cant start game

### ISSUE THREAD

**Issue by kerbyWW** [solsticegamestudios/GModCEFCodecFix#133]
infinity loading 
after start logo this screen
<img width="1470" alt="Снимок экрана 2024-10-04 в 21 59 48" src="https://github.com/user-attachments/assets/f04965ff-2a7e-491b-bf08-d4503629b430">

**Comment by AkikoKumagara** [comment]
You need to be more detailed when you post an issue or you won't be able to reasonably expect help.
Please, at minimum, list your operating system (name and version) and any attempts you've made to resolve this issue on your own.
Depending on your system, specs may also be relevant, so it's usually good to include those as well, namely CPU, GPU, and RAM capacity.

Otherwise, I recommend doing the basic troubleshooting steps: validate your game files, run GModCEFCodecFix again. Restart Steam and/or your PC.

**Comment by kerbyWW** [comment]
macbook air m2, i think that it can be my mods on PC, mb they loading on mac too

**Comment by AkikoKumagara** [comment]
> macbook air m2, i think that it can be my mods on PC, mb they loading on mac too

Good theory
If you would like to easily test, you can try launching with the -noworkshop launch option.

**Comment by kerbyWW** [comment]
NICE its start
but how can i launch with mods?

**Comment by AkikoKumagara** [comment]
> NICE its start but how can i launch with mods?

You'll need to narrow down which are causing the lockup and disable or unsubscribe from them.

**Comment by kerbyWW** [comment]
thanks alot ill try and comeback

**Comment by WinterPhoenix** [comment]
This is caused by some issue with GMod interacting with the filesystem on macOS. Usually it just crashes. Either way, it's an issue that Facepunch needs to fix. There's not really anything we can do about it.
