### ISSUE TITLE
Wrong resolution on Linux

### ISSUE THREAD

**Issue by iainizer** [solsticegamestudios/GModCEFCodecFix#29]
Hi, for a while I was trying to fix the 64 bit version of Gmod on Linux and found your fix while scrolling through various boards, and for the most part it worked, I'm actually able to open Gmod and access the main menu, the only problem I have is that now when I want to do anything I have to awkwardly move my mouse off to the side parallel to the menu buttons because the game keeps trying to account for both my monitors and sets the resolution to 3840 x 1080, but I'm not able to set it to 1080p unless I set it to run in a window, is there a fix that pertains to your codec fix or is this problem completely unrelated

**Comment by WinterPhoenix** [comment]
Does the same issue still happen with "legacy" menus that don't use CEF, like GMod's Options?

Also what distro?

**Comment by iainizer** [comment]
Hi there sorry for the extremely late response, to answer your first question I'll give a bit more explanation, without proton I'm able to open and run Gmod on the standard branch perfectly fine, it's when I try to play on the 64 bit version do I have problems, without CEF I wasn't able to even launch the game let alone see the main menu, CEF helped me overcome the first hurdle, but now I come to the issue of the game essentially trying to force me to play on ultra-wide mode. See attached image
![unknown](https://user-images.githubusercontent.com/105030319/167505870-fe551a74-8d04-4594-99f0-ab56c95afc41.png)

Also I use Gentoo

**Comment by WinterPhoenix** [comment]
Interesting. It's probably a GMod issue more likely, to be honest. It could be feeding CEF the wrong mouse position, or your window manager could be doing it as well, I'm not sure.

In either case, I don't have an ultrawide monitor to test, so I can't really look into it.

Let us know if you figure something out though!

**Comment by TheMindLord** [comment]
It seems to be an issue that users with multiple monitors such as myself are facing. The game tries to use the entire "screen area" and somehow detects all monitors as being one big screen. I'm not well versed in how this all works so take what I say with a grain of salt.

**Comment by thennothinghappened** [comment]
just started experiencing this as of today. gmod issue, happens without the fixer as I can see the game stretching across my monitors for a little bit before it crashes.

**Comment by WinterPhoenix** [comment]
I'm going to go ahead and close this, since it's an issue with GMod and not CEFCodecFix. Please consider reporting it at https://github.com/Facepunch/garrysmod-issues

That said, here are a couple launch options that may help in the meantime:

`-windowed`: Forces windowed mode
`-noborder`: Forces borderless when used with `-windowed`
`-w`: Forces a specific resolution width, ex. `-w 1920`
`-h`: Forces a specific resolution height, ex. `-h 1080`

An example if you want GMod to run in a borderless window at 1920x1080:
```
-w 1920 -h 1080 -windowed -noborder
```

The core problem is probably just an issue with this particularly set of software: Fedora/Nobara + GNOME/KDE + GMod.

Good luck!
