### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll is missing from your computer

### ISSUE THREAD

**Issue by Denver364** [solsticegamestudios/GModCEFCodecFix#45]
When loading Codecs I get this error message when trying to launch. Any help please?

The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by WinterPhoenix** [comment]
I’m guessing you’re on Windows 7. Windows 7 isn’t supported by CEFCodecFix. See #17  On Thu, Jan 12, 2023 at 11:42 PM, Denver364 ***@***.***> wrote:  
When loading Codecs I get this error message when trying to launch. Any help please?
The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by Denver364** [comment]
So I can download PyInstaller and do it that way?

**Comment by WinterPhoenix** [comment]
You could generate the EXE using PyInstaller, but you'll need to set up the environment for the script to work anyway, so I would just run the script once your environment is set up. See the napkin instructions in the issue linked above
