### ISSUE TITLE
MacOS download is a Unnamed "Document"

### ISSUE THREAD

**Issue by IsuckAtcomputering** [solsticegamestudios/GModCEFCodecFix#60]
I tried changing it to a .zip, .dmg, .pkg and .app but nothing worked. Am i doing something wrong?

**Comment by AkikoKumagara** [comment]
You need to make it executable by running `chmod +x /path/to/executable` on it.
This is explained in the official guide. It's not packaged.
Refer to step 6.
https://www.solsticegamestudios.com/forums/threads/tutorial-gmod-cef-codec-fix-macos.1266/

**Comment by IsuckAtcomputering** [comment]
Wow, It actually works! Can I hug you?

**Comment by IsuckAtcomputering** [comment]
It stopped working after a while, i've verified the files 5 times and nothing has happened. I also have the latest release.
<img width="481" alt="Screenshot 2023-08-02 at 8 45 39 am" src="https://github.com/solsticegamestudios/GModCEFCodecFix/assets/109134418/4b176c25-59e5-4399-b01b-99efedee36f2">

**Comment by AkikoKumagara** [comment]
> It stopped working after a while, i've verified the files 5 times and nothing has happened. I also have the latest release. <img alt="Screenshot 2023-08-02 at 8 45 39 am" width="481" src="https://user-images.githubusercontent.com/109134418/257658013-4b176c25-59e5-4399-b01b-99efedee36f2.png">

Try now. We had to wait for the manifest to regenerate. If it still isn't working, verify integrity and try once again. Thanks for your patience.

**Comment by IsuckAtcomputering** [comment]
It works again. Sorry for the trouble

**Comment by AkikoKumagara** [comment]
> It works again. Sorry for the trouble

Just for future reference, this error is almost always because of a game update, especially if it happens after validating files. Best solution is to wait and try again later as the automatic manifest regeneration happens on a six hour timer. If you're in the Solstice Game Studios Discord server, you are able to see our manifest regeneration commits in the #cefcodecfix channel and can then know exactly when you're able to patch again.
