### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by UltraBlackLinux** [solsticegamestudios/GModCEFCodecFix#70]
I just downloaded today's version of this tool, but I'm getting this checksum mismatch error:
```
bin/linux64/html_chromium_client.so: Does Not Match Original!
```

Can you fix that? I have tried verifying the game files, as the tool suggested.

**Comment by AkikoKumagara** [comment]
GMod x86-64 updated today. You'll need to wait for the manifest regeneration. Because commits are still rolling in at the moment I won't be triggering it manually. 
![Screenshot_20230801-160429](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/15231336/252275ce-0f7b-4ea8-986c-b9b1e4f57825)

The last auto manifest regeneration was completed at 1:09 PM Eastern, so the next one should be done at some time around 7:09 PM Eastern (it checks every six hours).

**Comment by Ohio2** [comment]
Would be actually handy to integrate some kind of option to skip checksums entirely. I get that most of the times it won't be needed or actually, i should say, it'd break stuff, but you can validate and retry again. The bypass would be a env var. I'd be happy to help in that by the way.

**Comment by WinterPhoenix** [comment]
The way to skip the checksum check is to not run the tool lol

The checksum check exists because we can’t patch files that differ from what we’re expecting. The end result won’t be what we want either.

When a GMod update happens, some files get overridden, breaking the patches. In fact, unless every file we patch gets overridden at once, which is essentially the same as verifying integrity, your GMod install becomes broken in this state.

So there’s no point in “skipping” the checksum checks. It’s just broken

**Comment by Ohio2** [comment]
I have indeed thought of that, and yea no, it doesn't differ 100% so bsdiff will adjust the changes as necessary, and it depends if gmod breaks or not. It depends on the size of the update, but not much else.

**Comment by AkikoKumagara** [comment]
Should be good to go now. If it doesn't work on the first try, validate files and run it again and all should be good.
