### ISSUE TITLE
Steam Path Not Found

### ISSUE THREAD

**Issue by BrinuJura** [solsticegamestudios/GModCEFCodecFix#79]
how to change steam path?

`GModCEFCodecFix`
Created by: Solstice Game Studios
How To Guide:
	https://www.solsticegamestudios.com/forums/threads/60/
Contact Us:
	Discord: https://www.solsticegamestudios.com/chat.html
	Email: contact@solsticegamestudios.com

You are running the latest version of CEFCodecFix [Local: 20230731 / Remote: 20230731]!

Error: Steam Path Not Found!
Is it installed somewhere other than /home/brinujura/.steam/steam or /home/brinujura/.local/share/Steam ?

If you need help, follow the Guide first:
- https://www.solsticegamestudios.com/forums/threads/60/

If that doesn't work, contact us:
- Discord: https://www.solsticegamestudios.com/chat.html
- Email: contact@solsticegamestudios.com`

**Comment by AkikoKumagara** [comment]
Are you, by chance, using the Flatpak version of Steam? If you are, it would be a great deal of help to provide your Steam install path to us as we work to add proper support for Flatpak. Right now, it's fairly common for Flatpak Steam to have issues similar to this, but if you're not using it, let me know and we'll look deeper into your issue here.

**Comment by BrinuJura** [comment]
Sorry i can't give you the steam patch cuz i installed deb version of steam and problem has gone
